apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.1.72.6-10.1.72.255
      avoid-buggy-ips: true
    - name: reserved
      protocol: layer2
      addresses:
      - 10.1.72.5/32
      avoid-buggy-ips: true
      auto-assign: false
